name: dcli_terminal
version: 4.0.1-beta.1
homepage: https://dcli.onepub.dev
description: Provides Terminal/Ansi functions used by DCli the Dart Console SDK but is also intended to be used directly.
repository: https://github.com/onepub-dev/dcli
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
    dart_console2: 
      git:
        url: https://github.com/wilinz/dart_console.git
dev_dependencies:
  lint_hard: ^4.0.0
  test: ^1.23.1
